theme: jekyll-theme-minimal
title: Jonathan Wilkins
description: Personal website
github:
  repository_url: https://www.google.com/
include:
  - md
  - index.html
  - md/about.md
  - md/software.md
  - md/projects.md
